[package]
name = "gamite-core"
version = "0.1.0"
edition = "2021"

[dependencies]
dirs = "6.0.0"
tokio-stream = "0.1.17"
url = "2.5.4"
serde = { version = "1.0.219", features = ["derive", "serde_derive"] }
chrono = "0.4.41"
